steps:
- id: maven-build
  name: 'eu.gcr.io/quatreapp/mvn-npm-builder'
  args: ['mvn', '-B', 'package']
  waitFor: ['-']
- id: docker-push
  name: 'eu.gcr.io/quatreapp/docker-xmllint'
  dir: 'srv'
  entrypoint: /bin/bash
  args: ['docker-build-push.sh']
  env:
    - 'PROJECT_ID=${PROJECT_ID}'
    - 'COMMIT_SHA=${SHORT_SHA}'
  waitFor:
    - maven-build
- id: setup-k8s
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['container', 'clusters', 'get-credentials', '${_CLUSTER_NAME}', '--zone=${_CLUSTER_ZONE}']
  env:
    - 'KUBECONFIG=/workspace/kubeconfig'
  waitFor:
    - docker-push
- id: mongo-install
  name: 'eu.gcr.io/${PROJECT_ID}/helm:3.0.3'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
      helm repo add stable https://kubernetes-charts.storage.googleapis.com/ \
      && helm repo update \
      && helm upgrade mongodb stable/mongodb-replicaset \
        --install \
        --namespace 4sh-invoice-${_ENV} \
        --version 3.11.4 \
        --set replicas=1,metrics.enabled=true
  env:
    - 'KUBECONFIG=/workspace/kubeconfig'
  waitFor:
    - setup-k8s
- id: invoice-patch
  dir: 'kubernetes/overlays/${_ENV}'
  name: 'lyft/kustomizer:v3.3.0'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      kustomize edit set image rxinvoice=rxinvoice:${SHORT_SHA} \
      && kustomize build > /tmp-gen/all.yaml
  volumes:
    - name: generated
      path: /tmp-gen
  waitFor:
    - docker-push
- id: invoice-deploy
  dir: '/tmp-gen'
  name: 'gcr.io/cloud-builders/kubectl'
  args: [ 'apply', '-f', '.' ]
  volumes:
  - name: generated
    path: /tmp-gen
  env:
    - 'KUBECTL_VERSION=1.14'
    - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
  waitFor:
    - setup-k8s
    - mongo-install
    - invoice-patch
tags: ['invoice']
options:
  machineType: 'N1_HIGHCPU_8'
substitutions:
  _CLUSTER_NAME: quatreapp-cl
  _CLUSTER_ZONE: europe-west1-c
  _ENV: dev
  _KUBECTL_DIGEST: 'sha256:f3739844fef97420c617261f997902a65100f203385c93f71e9420581b404d37'