steps:
- id: maven-build
  name: 'eu.gcr.io/quatreapp/mvn-npm-builder'
  args: ['mvn', '-B', 'package']
  waitFor: ['-']
- id: docker-push
  name: 'eu.gcr.io/quatreapp/docker-xmllint'
  dir: /workspace/srv
  entrypoint: /bin/bash
  args: ['docker-build-push.sh']
  env:
    - 'PROJECT_ID=${PROJECT_ID}'
    - 'COMMIT_SHA=${SHORT_SHA}'
  waitFor:
    - maven-build
- id: setup-k8s
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['container cluster get-credentials ${_CLUSTER_NAME} ${_CLUSTER_LOCATION}']
  env:
    - 'KUBECONFIG=/workspace/kubeconfig'
  waitFor:
    - docker-push
- id: mongo-install
  name: 'alpine/helm:3.0.3'
  entrypoint: /bin/sh
  args: [ '-c',
    '''
      helm repo add bitnami https://charts.bitnami.com/bitnami &&
      helm repo update &&
      echo "Before helm upgrade" &&
      helm upgrade --install \
        --namespace 4sh-invoice-${_ENV} \
        mongodb bitnami/mongodb-sharded \
        --version 1.0.5 \
        --set shards=1,metrics.enabled=true,service.name=mongo
    '''
  ]
  env:
    - 'KUBECONFIG=/workspace/kubeconfig'
  waitFor:
    - setup-k8s
- id: invoice-patch
  dir: '/workspace/kubernetes/overlays/${_ENV}'
  name: 'lyft/kustomizer:v3.3.0'
  args: [
    'edit', 'set', 'image',
    'rxinvoice=rxinvoice:${SHORT_SHA}'
  ]
  waitFor:
    - docker-push
- id: invoice-deploy
  dir: '/workspace/kubernetes/overlays/${_ENV}'
  name: 'gcr.io/cloud-builders/kubectl'
  args: [ 'apply', '-k', '.' ]
  waitFor:
    - mongo-install
    - invoice-patch
tags: ['invoice']
substitutions:
  _CLUSTER_NAME: quatreapp-cl
  _CLUSTER_LOCATION: '--zone europe-west1-c'
  _ENV: dev