steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--tag=eu.gcr.io/$PROJECT_ID/mvn-npm-builder:$COMMIT_SHA',
      '--tag=eu.gcr.io/$PROJECT_ID/mvn-npm-builder:latest',
      '-f', 'ci/cloud-build/Dockerfile.mvn-npm-builder', '.']
images: [
  'eu.gcr.io/$PROJECT_ID/mvn-npm-builder:$COMMIT_SHA',
  'eu.gcr.io/$PROJECT_ID/mvn-npm-builder:latest'
]