package rxinvoice.domain.enumeration;

public enum Activity {
    AUDIT, CONSULTING, TRAINING, POC, SPECIFICATION, GRAPHIC, MONITORING, DEVELOPMENT,
    MAINTENANCE, HOSTING, INDUSTRIALISATION_SUPPORT, INTEGRATION_SUPPORT, UNKNOWN
}
