apiVersion: apps/v1
kind: Deployment
metadata:
 name: buildkite-agent
spec:
 replicas: 1
 selector:
  matchLabels:
    app: buildkite-agent
 template:
   metadata:
     labels:
       app: buildkite-agent
   spec:
     containers:
       - name: buildkite-agent
         image: buildkite/agent
         imagePullPolicy: Always
         securityContext:
           privileged: true
         env:
           - name: BUILDKITE_AGENT_TOKEN
             valueFrom:
              secretKeyRef:
                name: buildkite-agent
                key: token
         volumeMounts:
           - name: docker-socket
             mountPath: /var/run/docker.sock
     volumes:
       - name: docker-socket
         hostPath: {path: /var/run/docker.sock}
